updated Run OWASP Dependency Check step

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -176,6 +176,23 @@ jobs:
         run: |
           mkdir -p owasp-report
           ./dependency-check/dependency-check/bin/dependency-check.sh --scan . --format HTML --out owasp-report --nvdApiKey ${{ secrets.NVD_API_KEY }}
+          retry_count=0
+          max_retries=3
+          until [ $retry_count -ge $max_retries ]
+          do
+            ./dependency-check/dependency-check/bin/dependency-check.sh --project "TechHiveStore" --scan "./"
+            result=$?
+            if [ $result -eq 0 ]; then
+              break
+            fi
+            retry_count=$((retry_count+1))
+            echo "Retrying... ($retry_count/$max_retries)"
+            sleep 10
+          done
+          if [ $result -ne 0 ]; then
+            echo "Dependency Check failed after $max_retries attempts."
+            exit 1
+          fi
 
       - name: Upload OWASP Dependency Check Report
         uses: actions/upload-artifact@v4
